# Generated by Django 4.1.8 on 2023-05-08 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_contact_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='message',
            new_name='text',
        ),
    ]
